---
title: "VAST"
author: "Hume Dickie"
date: "May 22, 2017"
output: html_document
---

```{r setup}
library(magrittr)
```


Results!
  1: GG7
  2: G8, G4, G3, GG6
  3: GG2
  4: G5
  5: G7
  6: G2
  7: GG1
  8: GG3, GG0, C6, GG5, C1, E4, E2, C8, G6
  9: G0
  10: G1
  11: GG4, E3, E0
  12: C3, C4, C0, C2, E1
  13: R4,C5
  14: R2
  15: R0
  16: R6
  17: R7
  18: R1
  19: R5, R3, C7, Base

```{r iGraphPageRank}
network <- read.csv("MC1_matrix.csv")
network <- network[,-1]


for (i in 1:40) {
  for (j in i:40) {
    network[[i]][[j]] <- network[[j]][[i]]
  }
}


network.matrix <- as.matrix(network)

library(igraph)

g <- graph_from_adjacency_matrix(network.matrix,"undirected",diag = FALSE)

page_rank(g)
results <- sort(page_rank(g)[[1]]) %>% rev()
plot(1:40,results)
```

```{r sensorData}
setwd("C:/Users/Hume Dickie/Desktop/Github/Mini-Challenge-1")
sensor <- read.csv("Lekagul Sensor Data.csv")
View(sensor)

timestamp.raw <- sensor[,1]
timestamp <- rep(list(),dim(sensor)[1])
for (i in seq_along(timestamp.raw)) {
  if (i %% 10000 == 0) {
    print(i/dim(sensor)[1])
  }
  timestamp[[i]] <- as.POSIXlt(timestamp.raw[[i]])
}


```

Definitely a summer location
```{r exploratoryAnaylsis}

plot(table(date.split))
plot(table(time.split))

sorted.time <- time.split %>% table() %>% sort() %>% rev()
topTenTimes <- sorted.time[1:10]


plot(table(time.split)[which(table(time.split) < 10)])
```